<?php

use Illuminate\Database\Seeder;

class DistrictTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('district')->insert([
            ['nameDistrict'=>'Thành phố Châu Đốc', 'idCity'=>'1'],
            ['nameDistrict'=>'Thành phố Long Xuyên', 'idCity'=>'1'],
            ['nameDistrict'=>'Huyện An Phú', 'idCity'=>'1'],
            ['nameDistrict'=>'Huyện Châu Phú', 'idCity'=>'1'],
            ['nameDistrict'=>'Huyện Châu Thành', 'idCity'=>'1'],
            ['nameDistrict'=>'Huyện Chợ Mới', 'idCity'=>'1'],
            ['nameDistrict'=>'Huyện Phú Tân', 'idCity'=>'1'],
            ['nameDistrict'=>'Huyện Thoại Sơn', 'idCity'=>'1'],
            ['nameDistrict'=>'Huyện Tịnh Biên', 'idCity'=>'1'],
            ['nameDistrict'=>'Huyện Tri Tôn', 'idCity'=>'1'],
            ['nameDistrict'=>'Thị Xã Tân Châu', 'idCity'=>'1'],
            ['nameDistrict'=>'Thành phố Bà Rịa', 'idCity'=>'2'],
            ['nameDistrict'=>'Thành phố Vũng Tàu', 'idCity'=>'2'],
            ['nameDistrict'=>'Huyện Châu Đức', 'idCity'=>'2'],
            ['nameDistrict'=>'Huyện Đất Đỏ', 'idCity'=>'2'],
            ['nameDistrict'=>'Huyện Long Biên', 'idCity'=>'2'],
            ['nameDistrict'=>'Huyện Tân Thành', 'idCity'=>'2'],
            ['nameDistrict'=>'Huyện Xuyên Mộc', 'idCity'=>'2'],
            ['nameDistrict'=>'Thành phố Bắc Giang', 'idCity'=>'3'],
            ['nameDistrict'=>'Huyện Hiệp Hoà', 'idCity'=>'3'],
            ['nameDistrict'=>'Huyện Lạng Giang', 'idCity'=>'3'],
            ['nameDistrict'=>'Huyện Lục Nam', 'idCity'=>'3'],
            ['nameDistrict'=>'Huyện Lục Ngạn', 'idCity'=>'3'],
            ['nameDistrict'=>'Huyện Sơn Động', 'idCity'=>'3'],
            ['nameDistrict'=>'Huyện Tân Yên', 'idCity'=>'3'],
            ['nameDistrict'=>'Huyện Việt Yên', 'idCity'=>'3'],
            ['nameDistrict'=>'Huyện Yên Dũng', 'idCity'=>'3'],
            ['nameDistrict'=>'Huyện Yên Thế', 'idCity'=>'3'],
            ['nameDistrict'=>'Huyện Ba Bể', 'idCity'=>'4'],
            ['nameDistrict'=>'Huyện Bạch Thông', 'idCity'=>'4'],
            ['nameDistrict'=>'Huyện Chợ Đồn', 'idCity'=>'4'],
            ['nameDistrict'=>'Huyện Chợ Mới', 'idCity'=>'4'],
            ['nameDistrict'=>'Huyện Na Rì', 'idCity'=>'4'],
            ['nameDistrict'=>'Huyện Ngân Sơn', 'idCity'=>'4'],
            ['nameDistrict'=>'Huyện Pác Năm', 'idCity'=>'4'],
            ['nameDistrict'=>'Thành phố Bắc Kạn', 'idCity'=>'4'],
            ['nameDistrict'=>'Thành phố Bạc Liêu', 'idCity'=>'5'],
            ['nameDistrict'=>'Huyện Đông Hải', 'idCity'=>'5'],
            ['nameDistrict'=>'Huyện Hoà Bình', 'idCity'=>'5'],
            ['nameDistrict'=>'Huyện Hồng Dân', 'idCity'=>'5'],
            ['nameDistrict'=>'Huyện Phước Long', 'idCity'=>'5'],
            ['nameDistrict'=>'Huyện Vĩnh Lợi', 'idCity'=>'5'],
            ['nameDistrict'=>'Thị xã Giá Rai', 'idCity'=>'5'],
            ['nameDistrict'=>'Huyện Gia Bình', 'idCity'=>'6'],
            ['nameDistrict'=>'Huyện Lương Tài', 'idCity'=>'6'],
            ['nameDistrict'=>'Huyện Quế Võ', 'idCity'=>'6'],
            ['nameDistrict'=>'Huyện Thuận Thành', 'idCity'=>'6'],
            ['nameDistrict'=>'Huyện Tiên Du', 'idCity'=>'6'],
            ['nameDistrict'=>'Huyện Yên Phong', 'idCity'=>'6'],
            ['nameDistrict'=>'Thành Phố Bắc Ninh', 'idCity'=>'6'],
            ['nameDistrict'=>'Thị xã Từ Sơn', 'idCity'=>'6'],
            ['nameDistrict'=>'Thành phố Bến Tre', 'idCity'=>'7'],
            ['nameDistrict'=>'Huyện Ba Tri', 'idCity'=>'7'],
            ['nameDistrict'=>'Huyện Bình Đại', 'idCity'=>'7'],
            ['nameDistrict'=>'Huyện Châu Thành', 'idCity'=>'7'],
            ['nameDistrict'=>'Huyện Chợ Lách', 'idCity'=>'7'],
            ['nameDistrict'=>'Huyện Giồng Trôm', 'idCity'=>'7'],
            ['nameDistrict'=>'Huyện Mỏ Cày Bắc', 'idCity'=>'7'],
            ['nameDistrict'=>'Huyện Mỏ Cày Nam', 'idCity'=>'7'],
            ['nameDistrict'=>'Huyện Thạnh Phú', 'idCity'=>'7'],
            ['nameDistrict'=>'Thành Phố Quy Nhơn', 'idCity'=>'8'],
            ['nameDistrict'=>'Huyện An Lão', 'idCity'=>'8'],
            ['nameDistrict'=>'Huyện Hoài Ân', 'idCity'=>'8'],
            ['nameDistrict'=>'Huyện Hoài Nhơn', 'idCity'=>'8'],
            ['nameDistrict'=>'Huyện Phú Cát', 'idCity'=>'8'],
            ['nameDistrict'=>'Huyện Phù Mỹ', 'idCity'=>'8'],
            ['nameDistrict'=>'Huyện Tây Sơn', 'idCity'=>'8'],
            ['nameDistrict'=>'Huyện Tuy Phước', 'idCity'=>'8'],
            ['nameDistrict'=>'Huyện Vân Canh', 'idCity'=>'8'],
            ['nameDistrict'=>'Huyện Vĩnh Thạnh', 'idCity'=>'8'],
            ['nameDistrict'=>'Thị Xã An Nhơn', 'idCity'=>'8'],
            ['nameDistrict'=>'Quận Ba Đình', 'idCity'=>'24'],
            ['nameDistrict'=>'Quận Bắc Từ Liêm', 'idCity'=>'24'],
            ['nameDistrict'=>'Quận Cầu Giấy', 'idCity'=>'24'],
            ['nameDistrict'=>'Quận Đống Đa', 'idCity'=>'24'],
            ['nameDistrict'=>'Quận Hà Đông', 'idCity'=>'24'],
            ['nameDistrict'=>'Quận Hai Bà Trưng', 'idCity'=>'24'],
            ['nameDistrict'=>'Quận Hoàn Kiếm', 'idCity'=>'24'],
            ['nameDistrict'=>'Quận Hoàng Mai', 'idCity'=>'24'],
            ['nameDistrict'=>'Quận Long Biên', 'idCity'=>'24'],
            ['nameDistrict'=>'Quận Nam Từ Liêm', 'idCity'=>'24'],
            ['nameDistrict'=>'Quận Tây Hồ', 'idCity'=>'24'],
            ['nameDistrict'=>'Quận Thanh Xuân', 'idCity'=>'24'],
            ['nameDistrict'=>'Huyện Ba Vì', 'idCity'=>'24'],
            ['nameDistrict'=>'Huyện Chương Mỹ', 'idCity'=>'24'],
            ['nameDistrict'=>'Huyện Đan Phượng', 'idCity'=>'24'],
            ['nameDistrict'=>'Huyện Đông Anh', 'idCity'=>'24'],
            ['nameDistrict'=>'Huyện Gia Lâm', 'idCity'=>'24'],
            ['nameDistrict'=>'Huyện Hoài Đức', 'idCity'=>'24'],
            ['nameDistrict'=>'Huyện Mê Linh', 'idCity'=>'24'],
            ['nameDistrict'=>'Huyện Mỹ Đức', 'idCity'=>'24'],
            ['nameDistrict'=>'Huyện Phú Xuyên', 'idCity'=>'24'],
            ['nameDistrict'=>'Huyện Phúc Thọ', 'idCity'=>'24'],
            ['nameDistrict'=>'Huyện Quốc Oai', 'idCity'=>'24'],
            ['nameDistrict'=>'Huyện Sóc Sơn', 'idCity'=>'24'],
            ['nameDistrict'=>'Huyện Thạch Thất', 'idCity'=>'24'],
            ['nameDistrict'=>'Huyện Thanh Oai', 'idCity'=>'24'],
            ['nameDistrict'=>'Huyện Thanh Trì', 'idCity'=>'24'],
            ['nameDistrict'=>'Huyện Thường Tín', 'idCity'=>'24'],
            ['nameDistrict'=>'Huyện Ứng Hoà', 'idCity'=>'24'],
            ['nameDistrict'=>'Thị xã Sơn Tây', 'idCity'=>'24'],
            ['nameDistrict'=>'Quận 1', 'idCity'=>'63'],
            ['nameDistrict'=>'Quận 2', 'idCity'=>'63'],
            ['nameDistrict'=>'Quận 3', 'idCity'=>'63'],
            ['nameDistrict'=>'Quận 4', 'idCity'=>'63'],
            ['nameDistrict'=>'Quận 5', 'idCity'=>'63'],
            ['nameDistrict'=>'Quận 6', 'idCity'=>'63'],
            ['nameDistrict'=>'Quận 7', 'idCity'=>'63'],
            ['nameDistrict'=>'Quận 8', 'idCity'=>'63'],
            ['nameDistrict'=>'Quận 9', 'idCity'=>'63'],
            ['nameDistrict'=>'Quận 10', 'idCity'=>'63'],
            ['nameDistrict'=>'Quận 11', 'idCity'=>'63'],
            ['nameDistrict'=>'Quận 12', 'idCity'=>'63'],
            ['nameDistrict'=>'Quận Bình Tân', 'idCity'=>'63'],
            ['nameDistrict'=>'Quận Bình Thạnh', 'idCity'=>'63'],
            ['nameDistrict'=>'Quận Gò Vấp', 'idCity'=>'63'],
            ['nameDistrict'=>'Quận Phú Nhuận', 'idCity'=>'63'],
            ['nameDistrict'=>'Quận Tân Bình', 'idCity'=>'63'],
            ['nameDistrict'=>'Quận Tân Phú', 'idCity'=>'63'],
            ['nameDistrict'=>'Quận Thủ Đức', 'idCity'=>'63'],
            ['nameDistrict'=>'Huyện Bình Chánh', 'idCity'=>'63'],
            ['nameDistrict'=>'Huyện Cần Giờ', 'idCity'=>'63'],
            ['nameDistrict'=>'Huyện Củ Chi', 'idCity'=>'63'],
            ['nameDistrict'=>'Huyện Hóc Môn', 'idCity'=>'63'],
            ['nameDistrict'=>'Huyện Nhà Bé', 'idCity'=>'63'],

        ]);
    }
}
